# Generated by Django 4.2 on 2024-06-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее обновление"
            ),
        ),
    ]
